FROM oraclelinux:8

RUN dnf install -y \
        python39 \
        sudo \
        curl \
        gnupg2 \
        ca-certificates && \
    alternatives --set python3 /usr/bin/python3.9 && \
    dnf clean all

ADD https://raw.githubusercontent.com/gdraheim/docker-systemctl-replacement/master/files/docker/systemctl3.py /usr/bin/systemctl
RUN chmod +x /usr/bin/systemctl

CMD ["/usr/bin/systemctl"]